services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "4000:80"
    volumes:
      # Mount entire app directory for live code changes (same as dev mode)
      - ./app:/var/www/html
      # Mount .env file for configuration
      - ./.env:/var/www/.env:ro
      # Mount CHANGELOG.md for version display
      - ./CHANGELOG.md:/var/www/CHANGELOG.md:ro
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - photowall-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      start_period: 40s
      retries: 3

  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      # Use named volume for better performance and portability
      - photowall-db-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    networks:
      - photowall-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  photowall-db-data:
    driver: local

networks:
  photowall-network:
    driver: bridge
